Repository IfcOpenShell/IfcOpenShell, pull requests merged in 2022-11, with the labels that each got.

#2557 Clean up README
  README.md
Labels: IfcOpenShell-Core

#2558 fix: add conditional #include <windows.h> for certain files breaking …
  src/ifcgeom_schema_agnostic/IfcGeomFilter.h
Labels: IfcOpenShell-Core

#2562 Numerical Attribute validation callback
  src/blenderbim/blenderbim/bim/helper.py
  src/blenderbim/blenderbim/bim/module/material/operator.py
  src/blenderbim/blenderbim/bim/prop.py
Labels: BlenderBIM

#2355 [BCF] New BCF XML handler with better performances
  .github/workflows/ci-bcf.yml
  .gitignore
  src/bcf/.gitignore
  src/bcf/Makefile
  src/bcf/README.md
  src/bcf/environment.yml
  src/bcf/pyproject.toml
  src/bcf/requirements-dev.txt
  src/bcf/requirements.txt
  src/bcf/setup.cfg
  src/bcf/setup.py
  src/bcf/src/bcf/bcfxml.py
  src/bcf/src/bcf/geometry.py
  src/bcf/src/bcf/inmemory_zipfile.py
  src/bcf/src/bcf/py.typed
  src/bcf/src/bcf/v2/__init__.py
  src/bcf/src/bcf/v2/bcfxml.py
  src/bcf/src/bcf/v2/data.py
  src/bcf/src/bcf/v2/model/__init__.py
  src/bcf/src/bcf/v2/model/markup.py
  src/bcf/src/bcf/v2/model/project.py
  src/bcf/src/bcf/v2/model/version.py
  src/bcf/src/bcf/v2/model/visinfo.py
  src/bcf/src/bcf/v2/topic.py
  src/bcf/src/bcf/v2/visinfo.py
  src/bcf/src/bcf/v3/__init__.py
  src/bcf/src/bcf/v3/bcfapi.py
  src/bcf/src/bcf/v3/bcfxml.py
  src/bcf/src/bcf/v3/data.py
  src/bcf/src/bcf/v3/document.py
  src/bcf/src/bcf/v3/model/__init__.py
  src/bcf/src/bcf/v3/model/documents.py
  src/bcf/src/bcf/v3/model/extensions.py
  src/bcf/src/bcf/v3/model/markup.py
  src/bcf/src/bcf/v3/model/project.py
  src/bcf/src/bcf/v3/model/version.py
  src/bcf/src/bcf/v3/model/visinfo.py
  src/bcf/src/bcf/v3/topic.py
  src/bcf/src/bcf/v3/visinfo.py
  src/bcf/src/bcf/xml_parser.py
  src/bcf/tests/__init__.py
  src/bcf/tests/conftest.py
  src/bcf/tests/v2/MaximumInformation.bcf
  src/bcf/tests/v2/__init__.py
  src/bcf/tests/v2/test_bcf_xml.py
  src/bcf/tests/v2/test_example_files.py
  src/bcf/tests/v3/Document reference internal.bcf
  src/bcf/tests/v3/__init__.py
  src/bcf/tests/v3/test_bcf_xml.py
  src/bcf/tests/v3/test_example_files.py
Labels: BCF

#2234 catch missing instances one by one. do not throw away whole relation.
  src/ifcparse/IfcParse.cpp
Labels: IfcOpenShell-Core
